"""Plan review — self-interrogation before emitting project_planned.

After generating a plan, the reviewer asks a different LLM provider:
  - What is this plan missing?
  - Are there any gaps in requirement coverage?
  - Is this the right approach?

If gaps are found, the plan is regenerated with the review feedback
injected as comments. The planner already supports this via its
`comments` and `previous_plan` parameters.

The review prompt is deliberately adversarial — it's not asking
"is this plan good?" It's asking "what's wrong with this plan?"
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("gods.review")


# ---------------------------------------------------------------------------
# Review result
# ---------------------------------------------------------------------------

@dataclass
class PlanReview:
    has_gaps: bool
    confidence: float  # 0.0 = no confidence in the plan, 1.0 = solid
    gaps: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    feedback: str = ""  # formatted for injection into planner comments
    raw_response: str = ""


# ---------------------------------------------------------------------------
# Review prompt
# ---------------------------------------------------------------------------

REVIEW_SYSTEM_PROMPT = """You are a senior technical reviewer. You are reviewing an execution plan generated by an AI planner.

Your job is to find problems. Be specific and constructive.

Questions to evaluate:
1. REQUIREMENT COVERAGE: Does every requirement [R1], [R2], etc. have at least one task addressing it? List any uncovered requirements.
2. GAPS: What do the requirements imply that no task covers? (error handling, edge cases, migrations, tests, documentation)
3. DEPENDENCIES: Can tasks actually run in this order? Are there missing dependencies or circular chains?
4. TASK SIZE: Are any tasks too large (should be 2+ tasks) or too vague (would confuse an AI executor)?
5. COMPLEXITY RATINGS: Are simple/medium/complex ratings accurate? Would a "simple" task actually need senior-level reasoning?
6. RISKS: What could go wrong that the plan doesn't account for?
7. APPROACH: Is there a fundamentally better way to accomplish these requirements?
8. TESTABILITY: Can the results of each task be verified? Are verification_criteria concrete and measurable?

Respond with this JSON structure:
{
    "has_gaps": true/false,
    "confidence": 0.0 to 1.0,
    "gaps": ["specific gap 1", "specific gap 2"],
    "suggestions": ["specific suggestion 1", "specific suggestion 2"],
    "overall_assessment": "1-2 sentence summary"
}

Be harsh. A plan that gets deployed with gaps costs more to fix than a plan that gets revised now.
Respond with ONLY the JSON, no markdown fences."""


def build_review_prompt(
    plan: dict,
    requirements: str,
    project_name: str = "",
) -> str:
    """Build the user message for plan review."""
    parts = []
    if project_name:
        parts.append(f"Project: {project_name}")
    parts.append(f"Requirements:\n{requirements}")
    parts.append(f"Plan:\n{json.dumps(plan, indent=2)}")
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Review function — calls LLM to critique the plan
# ---------------------------------------------------------------------------

async def review_plan(
    plan: dict,
    requirements: str,
    project_name: str = "",
    *,
    call_llm,  # async (system_prompt, user_message, **kwargs) → response
    provider: str | None = None,
    model: str | None = None,
) -> PlanReview:
    """Review a plan using LLM self-interrogation.

    Args:
        plan: The generated plan JSON
        requirements: Original project requirements
        project_name: Project name for context
        call_llm: LLM call function (from llm_router or gateway)
        provider: Optional provider override (use different from generator)
        model: Optional model override

    Returns:
        PlanReview with gaps, suggestions, and confidence
    """
    user_message = build_review_prompt(plan, requirements, project_name)

    kwargs = {}
    if provider:
        kwargs["provider"] = provider
    if model:
        kwargs["model"] = model

    try:
        response = await call_llm(
            system_prompt=REVIEW_SYSTEM_PROMPT,
            user_message=user_message,
            task_type="simple",
            **kwargs,
        )

        raw = response.text if hasattr(response, "text") else str(response)

        # Parse review JSON
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            # Try to extract JSON from response
            from backend.utils.json_utils import extract_json_object
            data = extract_json_object(raw)
            if data is None:
                logger.warning("Failed to parse review response: %s", raw[:200])
                return PlanReview(
                    has_gaps=False, confidence=0.5,
                    feedback="Review response was not parseable",
                    raw_response=raw,
                )

        gaps = data.get("gaps", [])
        suggestions = data.get("suggestions", [])
        confidence = float(data.get("confidence", 0.5))
        has_gaps = data.get("has_gaps", bool(gaps))
        assessment = data.get("overall_assessment", "")

        # Build formatted feedback for the planner's comments parameter
        feedback_parts = []
        if assessment:
            feedback_parts.append(f"Assessment: {assessment}")
        if gaps:
            feedback_parts.append("Gaps found:\n" + "\n".join(f"  - {g}" for g in gaps))
        if suggestions:
            feedback_parts.append("Suggestions:\n" + "\n".join(f"  - {s}" for s in suggestions))

        return PlanReview(
            has_gaps=has_gaps,
            confidence=confidence,
            gaps=gaps,
            suggestions=suggestions,
            feedback="\n\n".join(feedback_parts),
            raw_response=raw,
        )

    except Exception as e:
        logger.error("Plan review failed: %s", e)
        # On failure, don't block — return a permissive result
        return PlanReview(
            has_gaps=False, confidence=0.5,
            feedback=f"Review failed: {e}",
            raw_response="",
        )


# ---------------------------------------------------------------------------
# Convenience: review with threshold
# ---------------------------------------------------------------------------

async def review_plan_with_threshold(
    plan: dict,
    requirements: str,
    project_name: str = "",
    *,
    call_llm,
    provider: str | None = None,
    model: str | None = None,
    confidence_threshold: float = 0.7,
) -> tuple[PlanReview, bool]:
    """Review a plan and return whether it passes the threshold.

    Returns (review, should_regenerate).
    """
    review = await review_plan(
        plan, requirements, project_name,
        call_llm=call_llm, provider=provider, model=model,
    )

    should_regenerate = review.has_gaps and review.confidence < confidence_threshold

    if should_regenerate:
        logger.info(
            "Plan review: REGENERATE (confidence=%.2f < threshold=%.2f, %d gaps)",
            review.confidence, confidence_threshold, len(review.gaps),
        )
    else:
        logger.info(
            "Plan review: ACCEPT (confidence=%.2f, gaps=%d)",
            review.confidence, len(review.gaps),
        )

    return review, should_regenerate
