"""add rationale and confidence to project knowledge

Revision ID: add_knowledge_rationale
Revises: 017_add_sentinel_decisions
Create Date: 2026-03-15 23:59:59.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018'
down_revision: Union[str, None] = '017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rationale', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('alternatives_considered', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.Text(), server_default='medium', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_knowledge', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.drop_column('alternatives_considered')
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###
